version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: leovzdc/migrate:latest
    command: flask db upgrade
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - FLASK_ENV=development

  init-script:
    image: leovzdc/init-script:latest
    depends_on:
      - migrate
    environment:
      PGPASSWORD: postgres

  web:
    image: leovzdc/web:latest
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - FLASK_ENV=development
      - SECRET_KEY=uerguerhgiuoehgeurih

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
